/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[32];
new PlayerText:PlayerTD[MAX_PLAYERS][2];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(154.000000, 364.000000, "_");
	TextDrawFont(PublicTD[0], 1);
	TextDrawLetterSize(PublicTD[0], 0.600000, 3.899986);
	TextDrawTextSize(PublicTD[0], 298.500000, 19.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 2);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], -2016478465);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(191.000000, 364.000000, "_");
	TextDrawFont(PublicTD[1], 1);
	TextDrawLetterSize(PublicTD[1], 0.600000, 3.899986);
	TextDrawTextSize(PublicTD[1], 298.500000, 44.000000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 2);
	TextDrawColor(PublicTD[1], -1);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 336860290);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(154.000000, 373.000000, "_");
	TextDrawFont(PublicTD[2], 1);
	TextDrawLetterSize(PublicTD[2], 0.600000, 1.249989);
	TextDrawTextSize(PublicTD[2], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], -1);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], -1);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(154.000000, 391.000000, "_");
	TextDrawFont(PublicTD[3], 1);
	TextDrawLetterSize(PublicTD[3], 0.600000, -0.150009);
	TextDrawTextSize(PublicTD[3], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 2);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], -1);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(202.000000, 362.000000, "KMH");
	TextDrawFont(PublicTD[4], 1);
	TextDrawLetterSize(PublicTD[4], 0.158333, 1.000000);
	TextDrawTextSize(PublicTD[4], 211.500000, 17.000000);
	TextDrawSetOutline(PublicTD[4], 0);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1094795521);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 0);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(148.000000, 355.000000, "_");
	TextDrawFont(PublicTD[5], 1);
	TextDrawLetterSize(PublicTD[5], 0.600000, 0.249990);
	TextDrawTextSize(PublicTD[5], 298.500000, 2.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 2);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], -1);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(146.000000, 350.000000, "_");
	TextDrawFont(PublicTD[6], 1);
	TextDrawLetterSize(PublicTD[6], 0.600000, 0.249990);
	TextDrawTextSize(PublicTD[6], 298.500000, -2.500000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 2);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], -1);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(150.000000, 350.000000, "_");
	TextDrawFont(PublicTD[7], 1);
	TextDrawLetterSize(PublicTD[7], 0.600000, 0.249990);
	TextDrawTextSize(PublicTD[7], 298.500000, -2.500000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 2);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], -1);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(148.000000, 349.000000, "_");
	TextDrawFont(PublicTD[8], 1);
	TextDrawLetterSize(PublicTD[8], 0.600000, -0.300009);
	TextDrawTextSize(PublicTD[8], 298.500000, 2.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 2);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], -1);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(145.000000, 407.000000, "_");
	TextDrawFont(PublicTD[9], 1);
	TextDrawLetterSize(PublicTD[9], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[9], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[9], 1);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 2);
	TextDrawColor(PublicTD[9], -1);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], -2016478465);
	TextDrawUseBox(PublicTD[9], 1);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(148.000000, 407.000000, "_");
	TextDrawFont(PublicTD[10], 1);
	TextDrawLetterSize(PublicTD[10], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[10], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[10], 1);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 2);
	TextDrawColor(PublicTD[10], -1);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], -2016478465);
	TextDrawUseBox(PublicTD[10], 1);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(151.000000, 407.000000, "_");
	TextDrawFont(PublicTD[11], 1);
	TextDrawLetterSize(PublicTD[11], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[11], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[11], 1);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 2);
	TextDrawColor(PublicTD[11], -1);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], -2016478465);
	TextDrawUseBox(PublicTD[11], 1);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(154.000000, 407.000000, "_");
	TextDrawFont(PublicTD[12], 1);
	TextDrawLetterSize(PublicTD[12], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[12], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[12], 1);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], -1);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], -2016478465);
	TextDrawUseBox(PublicTD[12], 1);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	PublicTD[13] = TextDrawCreate(157.000000, 407.000000, "_");
	TextDrawFont(PublicTD[13], 1);
	TextDrawLetterSize(PublicTD[13], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[13], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[13], 1);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 2);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], -2016478465);
	TextDrawUseBox(PublicTD[13], 1);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(160.000000, 407.000000, "_");
	TextDrawFont(PublicTD[14], 1);
	TextDrawLetterSize(PublicTD[14], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[14], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[14], 1);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 2);
	TextDrawColor(PublicTD[14], -1);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], -2016478465);
	TextDrawUseBox(PublicTD[14], 1);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 0);

	PublicTD[15] = TextDrawCreate(163.000000, 407.000000, "_");
	TextDrawFont(PublicTD[15], 1);
	TextDrawLetterSize(PublicTD[15], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[15], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[15], 1);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 2);
	TextDrawColor(PublicTD[15], -1);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], -2016478465);
	TextDrawUseBox(PublicTD[15], 1);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 0);

	PublicTD[16] = TextDrawCreate(166.000000, 407.000000, "_");
	TextDrawFont(PublicTD[16], 1);
	TextDrawLetterSize(PublicTD[16], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[16], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[16], 1);
	TextDrawSetShadow(PublicTD[16], 0);
	TextDrawAlignment(PublicTD[16], 2);
	TextDrawColor(PublicTD[16], -1);
	TextDrawBackgroundColor(PublicTD[16], 255);
	TextDrawBoxColor(PublicTD[16], -2016478465);
	TextDrawUseBox(PublicTD[16], 1);
	TextDrawSetProportional(PublicTD[16], 1);
	TextDrawSetSelectable(PublicTD[16], 0);

	PublicTD[17] = TextDrawCreate(169.000000, 407.000000, "_");
	TextDrawFont(PublicTD[17], 1);
	TextDrawLetterSize(PublicTD[17], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[17], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[17], 1);
	TextDrawSetShadow(PublicTD[17], 0);
	TextDrawAlignment(PublicTD[17], 2);
	TextDrawColor(PublicTD[17], -1);
	TextDrawBackgroundColor(PublicTD[17], 255);
	TextDrawBoxColor(PublicTD[17], -2016478465);
	TextDrawUseBox(PublicTD[17], 1);
	TextDrawSetProportional(PublicTD[17], 1);
	TextDrawSetSelectable(PublicTD[17], 0);

	PublicTD[18] = TextDrawCreate(172.000000, 407.000000, "_");
	TextDrawFont(PublicTD[18], 1);
	TextDrawLetterSize(PublicTD[18], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[18], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[18], 1);
	TextDrawSetShadow(PublicTD[18], 0);
	TextDrawAlignment(PublicTD[18], 2);
	TextDrawColor(PublicTD[18], -1);
	TextDrawBackgroundColor(PublicTD[18], 255);
	TextDrawBoxColor(PublicTD[18], -2016478465);
	TextDrawUseBox(PublicTD[18], 1);
	TextDrawSetProportional(PublicTD[18], 1);
	TextDrawSetSelectable(PublicTD[18], 0);

	PublicTD[19] = TextDrawCreate(175.000000, 407.000000, "_");
	TextDrawFont(PublicTD[19], 1);
	TextDrawLetterSize(PublicTD[19], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[19], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[19], 1);
	TextDrawSetShadow(PublicTD[19], 0);
	TextDrawAlignment(PublicTD[19], 2);
	TextDrawColor(PublicTD[19], -1);
	TextDrawBackgroundColor(PublicTD[19], 255);
	TextDrawBoxColor(PublicTD[19], -2016478465);
	TextDrawUseBox(PublicTD[19], 1);
	TextDrawSetProportional(PublicTD[19], 1);
	TextDrawSetSelectable(PublicTD[19], 0);

	PublicTD[20] = TextDrawCreate(178.000000, 407.000000, "_");
	TextDrawFont(PublicTD[20], 1);
	TextDrawLetterSize(PublicTD[20], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[20], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[20], 1);
	TextDrawSetShadow(PublicTD[20], 0);
	TextDrawAlignment(PublicTD[20], 2);
	TextDrawColor(PublicTD[20], -1);
	TextDrawBackgroundColor(PublicTD[20], 255);
	TextDrawBoxColor(PublicTD[20], -2016478465);
	TextDrawUseBox(PublicTD[20], 1);
	TextDrawSetProportional(PublicTD[20], 1);
	TextDrawSetSelectable(PublicTD[20], 0);

	PublicTD[21] = TextDrawCreate(181.000000, 407.000000, "_");
	TextDrawFont(PublicTD[21], 1);
	TextDrawLetterSize(PublicTD[21], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[21], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[21], 1);
	TextDrawSetShadow(PublicTD[21], 0);
	TextDrawAlignment(PublicTD[21], 2);
	TextDrawColor(PublicTD[21], -1);
	TextDrawBackgroundColor(PublicTD[21], 255);
	TextDrawBoxColor(PublicTD[21], -2016478465);
	TextDrawUseBox(PublicTD[21], 1);
	TextDrawSetProportional(PublicTD[21], 1);
	TextDrawSetSelectable(PublicTD[21], 0);

	PublicTD[22] = TextDrawCreate(184.000000, 407.000000, "_");
	TextDrawFont(PublicTD[22], 1);
	TextDrawLetterSize(PublicTD[22], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[22], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[22], 1);
	TextDrawSetShadow(PublicTD[22], 0);
	TextDrawAlignment(PublicTD[22], 2);
	TextDrawColor(PublicTD[22], -1);
	TextDrawBackgroundColor(PublicTD[22], 255);
	TextDrawBoxColor(PublicTD[22], -2016478465);
	TextDrawUseBox(PublicTD[22], 1);
	TextDrawSetProportional(PublicTD[22], 1);
	TextDrawSetSelectable(PublicTD[22], 0);

	PublicTD[23] = TextDrawCreate(187.000000, 407.000000, "_");
	TextDrawFont(PublicTD[23], 1);
	TextDrawLetterSize(PublicTD[23], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[23], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[23], 1);
	TextDrawSetShadow(PublicTD[23], 0);
	TextDrawAlignment(PublicTD[23], 2);
	TextDrawColor(PublicTD[23], -1);
	TextDrawBackgroundColor(PublicTD[23], 255);
	TextDrawBoxColor(PublicTD[23], -2016478465);
	TextDrawUseBox(PublicTD[23], 1);
	TextDrawSetProportional(PublicTD[23], 1);
	TextDrawSetSelectable(PublicTD[23], 0);

	PublicTD[24] = TextDrawCreate(190.000000, 407.000000, "_");
	TextDrawFont(PublicTD[24], 1);
	TextDrawLetterSize(PublicTD[24], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[24], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[24], 1);
	TextDrawSetShadow(PublicTD[24], 0);
	TextDrawAlignment(PublicTD[24], 2);
	TextDrawColor(PublicTD[24], -1);
	TextDrawBackgroundColor(PublicTD[24], 255);
	TextDrawBoxColor(PublicTD[24], -2016478465);
	TextDrawUseBox(PublicTD[24], 1);
	TextDrawSetProportional(PublicTD[24], 1);
	TextDrawSetSelectable(PublicTD[24], 0);

	PublicTD[25] = TextDrawCreate(193.000000, 407.000000, "_");
	TextDrawFont(PublicTD[25], 1);
	TextDrawLetterSize(PublicTD[25], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[25], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[25], 1);
	TextDrawSetShadow(PublicTD[25], 0);
	TextDrawAlignment(PublicTD[25], 2);
	TextDrawColor(PublicTD[25], -1);
	TextDrawBackgroundColor(PublicTD[25], 255);
	TextDrawBoxColor(PublicTD[25], -2016478465);
	TextDrawUseBox(PublicTD[25], 1);
	TextDrawSetProportional(PublicTD[25], 1);
	TextDrawSetSelectable(PublicTD[25], 0);

	PublicTD[26] = TextDrawCreate(196.000000, 407.000000, "_");
	TextDrawFont(PublicTD[26], 1);
	TextDrawLetterSize(PublicTD[26], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[26], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[26], 1);
	TextDrawSetShadow(PublicTD[26], 0);
	TextDrawAlignment(PublicTD[26], 2);
	TextDrawColor(PublicTD[26], -1);
	TextDrawBackgroundColor(PublicTD[26], 255);
	TextDrawBoxColor(PublicTD[26], -2016478465);
	TextDrawUseBox(PublicTD[26], 1);
	TextDrawSetProportional(PublicTD[26], 1);
	TextDrawSetSelectable(PublicTD[26], 0);

	PublicTD[27] = TextDrawCreate(199.000000, 407.000000, "_");
	TextDrawFont(PublicTD[27], 1);
	TextDrawLetterSize(PublicTD[27], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[27], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[27], 1);
	TextDrawSetShadow(PublicTD[27], 0);
	TextDrawAlignment(PublicTD[27], 2);
	TextDrawColor(PublicTD[27], -1);
	TextDrawBackgroundColor(PublicTD[27], 255);
	TextDrawBoxColor(PublicTD[27], -2016478465);
	TextDrawUseBox(PublicTD[27], 1);
	TextDrawSetProportional(PublicTD[27], 1);
	TextDrawSetSelectable(PublicTD[27], 0);

	PublicTD[28] = TextDrawCreate(202.000000, 407.000000, "_");
	TextDrawFont(PublicTD[28], 1);
	TextDrawLetterSize(PublicTD[28], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[28], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[28], 1);
	TextDrawSetShadow(PublicTD[28], 0);
	TextDrawAlignment(PublicTD[28], 2);
	TextDrawColor(PublicTD[28], -1);
	TextDrawBackgroundColor(PublicTD[28], 255);
	TextDrawBoxColor(PublicTD[28], -764862721);
	TextDrawUseBox(PublicTD[28], 1);
	TextDrawSetProportional(PublicTD[28], 1);
	TextDrawSetSelectable(PublicTD[28], 0);

	PublicTD[29] = TextDrawCreate(205.000000, 407.000000, "_");
	TextDrawFont(PublicTD[29], 1);
	TextDrawLetterSize(PublicTD[29], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[29], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[29], 1);
	TextDrawSetShadow(PublicTD[29], 0);
	TextDrawAlignment(PublicTD[29], 2);
	TextDrawColor(PublicTD[29], -1);
	TextDrawBackgroundColor(PublicTD[29], 255);
	TextDrawBoxColor(PublicTD[29], -764862721);
	TextDrawUseBox(PublicTD[29], 1);
	TextDrawSetProportional(PublicTD[29], 1);
	TextDrawSetSelectable(PublicTD[29], 0);

	PublicTD[30] = TextDrawCreate(208.000000, 407.000000, "_");
	TextDrawFont(PublicTD[30], 1);
	TextDrawLetterSize(PublicTD[30], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[30], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[30], 1);
	TextDrawSetShadow(PublicTD[30], 0);
	TextDrawAlignment(PublicTD[30], 2);
	TextDrawColor(PublicTD[30], -1);
	TextDrawBackgroundColor(PublicTD[30], 255);
	TextDrawBoxColor(PublicTD[30], -1962934017);
	TextDrawUseBox(PublicTD[30], 1);
	TextDrawSetProportional(PublicTD[30], 1);
	TextDrawSetSelectable(PublicTD[30], 0);

	PublicTD[31] = TextDrawCreate(211.000000, 407.000000, "_");
	TextDrawFont(PublicTD[31], 1);
	TextDrawLetterSize(PublicTD[31], 0.583333, 0.799987);
	TextDrawTextSize(PublicTD[31], 298.500000, -1.500000);
	TextDrawSetOutline(PublicTD[31], 1);
	TextDrawSetShadow(PublicTD[31], 0);
	TextDrawAlignment(PublicTD[31], 2);
	TextDrawColor(PublicTD[31], -1);
	TextDrawBackgroundColor(PublicTD[31], 255);
	TextDrawBoxColor(PublicTD[31], -1962934017);
	TextDrawUseBox(PublicTD[31], 1);
	TextDrawSetProportional(PublicTD[31], 1);
	TextDrawSetSelectable(PublicTD[31], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	TextDrawDestroy(PublicTD[16]);
	TextDrawDestroy(PublicTD[17]);
	TextDrawDestroy(PublicTD[18]);
	TextDrawDestroy(PublicTD[19]);
	TextDrawDestroy(PublicTD[20]);
	TextDrawDestroy(PublicTD[21]);
	TextDrawDestroy(PublicTD[22]);
	TextDrawDestroy(PublicTD[23]);
	TextDrawDestroy(PublicTD[24]);
	TextDrawDestroy(PublicTD[25]);
	TextDrawDestroy(PublicTD[26]);
	TextDrawDestroy(PublicTD[27]);
	TextDrawDestroy(PublicTD[28]);
	TextDrawDestroy(PublicTD[29]);
	TextDrawDestroy(PublicTD[30]);
	TextDrawDestroy(PublicTD[31]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 173.000000, 362.000000, "100");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.545831, 3.999998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 211.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 154.000000, 349.000000, "LD_SPAC:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 53.000000, 6.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		TextDrawShowForPlayer(playerid, PublicTD[16]);
		TextDrawShowForPlayer(playerid, PublicTD[17]);
		TextDrawShowForPlayer(playerid, PublicTD[18]);
		TextDrawShowForPlayer(playerid, PublicTD[19]);
		TextDrawShowForPlayer(playerid, PublicTD[20]);
		TextDrawShowForPlayer(playerid, PublicTD[21]);
		TextDrawShowForPlayer(playerid, PublicTD[22]);
		TextDrawShowForPlayer(playerid, PublicTD[23]);
		TextDrawShowForPlayer(playerid, PublicTD[24]);
		TextDrawShowForPlayer(playerid, PublicTD[25]);
		TextDrawShowForPlayer(playerid, PublicTD[26]);
		TextDrawShowForPlayer(playerid, PublicTD[27]);
		TextDrawShowForPlayer(playerid, PublicTD[28]);
		TextDrawShowForPlayer(playerid, PublicTD[29]);
		TextDrawShowForPlayer(playerid, PublicTD[30]);
		TextDrawShowForPlayer(playerid, PublicTD[31]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		return 1;
	}
	return 0;
}
